<?php

return [
    'medicines' => [
        'filename' => 'master-obat',
        'table' => 'medicines',
        'joins' => [
            ['pharmacies', 'pharmacies.id', '=', 'medicines.pharmacy_id'],
            ['medicine_categories', 'medicine_categories.id', '=', 'medicines.medicine_category_id'],
            ['compositions', 'compositions.id', '=', 'medicines.composition_id'],
            ['factories', 'factories.id', '=', 'medicines.factory_id'],
            ['creditors', 'creditors.id', '=', 'medicines.creditors_id'],
            ['etalases', 'etalases.id', '=', 'medicines.etalase'],
            ['locations', 'locations.id', '=', 'medicines.location'],
        ],
        'columns' => [
            'ID' => 'medicines.id',
            'Kode' => 'medicines.code',
            'Barcode' => 'medicines.barcode',
            'Nama Obat' => 'medicines.name',
            'Generik' => 'medicines.generic',
            'Cabang' => 'pharmacies.name',
            'Kategori' => 'medicine_categories.name',
            'Komposisi' => 'compositions.name',
            'Komponen' => 'medicines.component',
            'Pabrik' => 'factories.name',
            'Kreditur Utama' => 'creditors.name',
            'Kemasan' => 'medicines.packaging',
            'Satuan' => 'medicines.unit',
            'Isi' => 'medicines.content',
            'Dosis' => 'medicines.dosage',
            'Strip' => 'medicines.strip',
            'Harga Dasar' => 'medicines.raw_price',
            'Harga Netto Apotek' => 'medicines.pharmacy_net_price',
            'Harga Netto' => 'medicines.net_price',
            'HET' => 'medicines.het_price',
            'Stok Minimal' => 'medicines.minimal_stock',
            'Stok' => 'medicines.stock',
            'Psikotropika' => 'medicines.psychotropic',
            'Prekursor' => 'medicines.precursor',
            'Resep' => 'medicines.receipt',
            'Sediaan' => 'medicines.preparations',
            'Whole' => 'medicines.whole',
            'Tipe' => 'medicines.type',
            'Etalase' => 'etalases.name',
            'Lokasi' => 'locations.name',
            'Status' => 'medicines.status',
            'Dibuat' => 'medicines.created_at',
            'Diubah' => 'medicines.updated_at',
        ],
    ],

    'debtors' => [
        'filename' => 'master-debitur',
        'table' => 'debtors',
        'columns' => [
            'ID' => 'debtors.id',
            'Kode' => 'debtors.code',
            'Nama' => 'debtors.name',
            'Alamat' => 'debtors.address',
            'Kota' => 'debtors.city',
            'Telepon' => 'debtors.phone',
            'Kontak' => 'debtors.contact',
            'Email' => 'debtors.email',
            'Status' => 'debtors.status',
            'Dibuat' => 'debtors.created_at',
            'Diubah' => 'debtors.updated_at',
        ],
    ],

    'creditors' => [
        'filename' => 'master-kreditur',
        'table' => 'creditors',
        'columns' => [
            'ID' => 'creditors.id',
            'Kode' => 'creditors.code',
            'Nama' => 'creditors.name',
            'Alamat' => 'creditors.address',
            'Telepon' => 'creditors.phone',
            'Jenis PPN' => 'creditors.ppn_type',
            'Nomor Seri' => 'creditors.numbers',
            'Bank' => 'creditors.bank_type',
            'Nomor Rekening' => 'creditors.bank_number',
            'Nama Rekening' => 'creditors.bank_name',
            'NPWP' => 'creditors.npwp',
            'Waktu Kredit' => 'creditors.credit_time',
            'Status' => 'creditors.status',
            'Dibuat' => 'creditors.created_at',
            'Diubah' => 'creditors.updated_at',
        ],
    ],

    'categories' => [
        'filename' => 'kategori-obat',
        'table' => 'medicine_categories',
        'columns' => [
            'ID' => 'medicine_categories.id',
            'Kode' => 'medicine_categories.code',
            'Nama' => 'medicine_categories.name',
            'Status' => 'medicine_categories.status',
            'Dibuat' => 'medicine_categories.created_at',
            'Diubah' => 'medicine_categories.updated_at',
        ],
    ],

    'compositions' => [
        'filename' => 'master-komposisi',
        'table' => 'compositions',
        'columns' => [
            'ID' => 'compositions.id',
            'Kode' => 'compositions.code',
            'Nama' => 'compositions.name',
            'Status' => 'compositions.status',
            'Dibuat' => 'compositions.created_at',
            'Diubah' => 'compositions.updated_at',
        ],
    ],

    'doctors' => [
        'filename' => 'master-dokter',
        'table' => 'doctors',
        'joins' => [
            ['pharmacies', 'pharmacies.id', '=', 'doctors.pharmacy_id'],
        ],
        'columns' => [
            'ID' => 'doctors.id',
            'Kode' => 'doctors.code',
            'Nama' => 'doctors.name',
            'Cabang' => 'pharmacies.name',
            'Spesialis' => 'doctors.specialist',
            'Praktik' => 'doctors.practice',
            'Alamat' => 'doctors.address',
            'Kota' => 'doctors.city',
            'Telepon' => 'doctors.phone',
            'Status' => 'doctors.status',
            'Dibuat' => 'doctors.created_at',
            'Diubah' => 'doctors.updated_at',
        ],
    ],

    'patients' => [
        'filename' => 'master-pasien',
        'table' => 'patients',
        'columns' => [
            'ID' => 'patients.id',
            'Kode' => 'patients.code',
            'Nama' => 'patients.name',
            'Alamat' => 'patients.address',
            'Kota' => 'patients.city',
            'Telepon' => 'patients.phone',
            'Tanggal Lahir' => 'patients.birth',
            'Total Harga' => 'patients.total_price',
            'Status' => 'patients.status',
            'Dibuat' => 'patients.created_at',
            'Diubah' => 'patients.updated_at',
        ],
    ],

    'factories' => [
        'filename' => 'master-pabrik',
        'table' => 'factories',
        'columns' => [
            'ID' => 'factories.id',
            'Kode' => 'factories.code',
            'Nama' => 'factories.name',
            'Status' => 'factories.status',
            'Dibuat' => 'factories.created_at',
            'Diubah' => 'factories.updated_at',
        ],
    ],

    'parameters' => [
        'filename' => 'master-parameter',
        'table' => 'transaction_parameter',
        'joins' => [
            ['debtors', 'debtors.id', '=', 'transaction_parameter.debtor_id'],
        ],
        'columns' => [
            'ID' => 'transaction_parameter.id',
            'Debitur' => 'debtors.name',
            'Resep' => 'transaction_parameter.receipt',
            'PDU' => 'transaction_parameter.pdu',
            'OTC' => 'transaction_parameter.otc',
            'Kredit' => 'transaction_parameter.credit',
            'Embalase' => 'transaction_parameter.embalas',
            'Servis' => 'transaction_parameter.service',
            'Pembulatan' => 'transaction_parameter.rounding',
            'Status' => 'transaction_parameter.status',
            'Dibuat' => 'transaction_parameter.created_at',
            'Diubah' => 'transaction_parameter.updated_at',
        ],
    ],

    'locations' => [
        'filename' => 'master-lokasi',
        'table' => 'locations',
        'columns' => [
            'ID' => 'locations.id',
            'Nama' => 'locations.name',
            'Status' => 'locations.status',
            'Dibuat' => 'locations.created_at',
            'Diubah' => 'locations.updated_at',
        ],
    ],

    'items' => [
        'filename' => 'master-etalase',
        'table' => 'etalases',
        'joins' => [
            ['pharmacies', 'pharmacies.id', '=', 'etalases.pharmacy_id'],
        ],
        'active_pharmacy_scope' => true,
        'columns' => [
            'ID' => 'etalases.id',
            'Cabang' => 'pharmacies.name',
            'Nama' => 'etalases.name',
            'Status' => 'etalases.status',
            'Dibuat' => 'etalases.created_at',
            'Diubah' => 'etalases.updated_at',
        ],
    ],
];
